export const MONACO_DARK_THEME = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "comment", foreground: "555566", fontStyle: "italic" },
    { token: "keyword", foreground: "6C5CE7" },
    { token: "string", foreground: "55EFC4" },
    { token: "number", foreground: "FDCB6E" },
    { token: "type", foreground: "74B9FF" },
    { token: "function", foreground: "00B894" },
    { token: "variable", foreground: "E8E8ED" },
    { token: "operator", foreground: "E17055" },
  ],
  colors: {
    "editor.background": "#0F0F17",
    "editor.foreground": "#E8E8ED",
    "editor.lineHighlightBackground": "#1A1A2600",
    "editor.selectionBackground": "#6C5CE733",
    "editorCursor.foreground": "#74B9FF",
    "editorLineNumber.foreground": "#555566",
    "editorLineNumber.activeForeground": "#8888A0",
    "editorGutter.background": "#0F0F17",
    "editor.selectionHighlightBackground": "#6C5CE720",
    "editorIndentGuide.background": "#2A2A3C40",
    "editorIndentGuide.activeBackground": "#2A2A3C80",
    "scrollbarSlider.background": "#2A2A3C80",
    "scrollbarSlider.hoverBackground": "#555566",
    "scrollbarSlider.activeBackground": "#8888A0",
  },
};

export const MONACO_OPTIONS = {
  fontSize: 14,
  lineHeight: 22,
  fontFamily: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace",
  minimap: { enabled: false },
  scrollBeyondLastLine: false,
  lineNumbers: "on" as const,
  glyphMargin: true,
  folding: false,
  lineDecorationsWidth: 8,
  lineNumbersMinChars: 3,
  renderLineHighlight: "none" as const,
  padding: { top: 12, bottom: 12 },
  overviewRulerLanes: 0,
  hideCursorInOverviewRuler: true,
  overviewRulerBorder: false,
  contextmenu: false,
  wordWrap: "on" as const,
  tabSize: 2,
  automaticLayout: true,
};
